parameters:
    aw.rest_hal.listener.class: Alterway\Bundle\RestHalBundle\EventListener\ResourceListener

services:
    aw.rest_hal.listener:
        class: "%aw.rest_hal.listener.class%"
        tags:
            - { name: kernel.event_listener, event: kernel.view, method: onKernelView }
